spring:
  datasource:
    driver: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/x?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
      virtual-host: x
  lettuce:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 200
        max-idle: 50
        min-idle: 10
        max-wait: 300ms
    timeout: 0ms

token:
  secret-key: xxd
  expire-time: 0