spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/x
    username: postgres
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          temp.use_jdbc_metadata_defaults: false
  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
      virtual-host: x
  redis:
    host: localhost
    port: 6379

jwt:
  secret-key: xuexingdong
  expiration: 1m
