spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
      - LoggerFilter
      routes:
      - id: ucenter
        uri: lb://ucenter
        predicates:
          - Path=/*/**
        filter:
          - LoginFilter
server:
  port: 8088