spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
      - Logger
      routes:
      - id: ucenter
        uri: lb://ucenter
        predicates:
          - Path=/ucenter/**
        filters:
          - Auth

server:
  port: 8088